# To add new secrets, run `nix-shell -p sops --run "sops secrets/example.yaml"`
keys:
  - &ant 4bdfa9664074bc7104b1d8748e1d306a373f62d1
  - &titan age1rlf3wrtj0dszr0wr6jqua39nfha43pmr55naw9ql646mqcr04dus54gs8n
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - pgp:
      - *ant
      age:
      - *titan
