# -- global space -- #
# values below can be overwritten by command line flags

# NOTE: All palettes will fill 16 colors (from color0 to color15), 16 color
#       variations are the 'ilusion' of more colors by opaquing color1 to color5.
# Use the most prominent colors in a way that makes sense, a scheme:
#  * dark            - dark colors dark background and light contrast
#  * dark16          - Same as dark but uses the colors trick
#  * darkcomp        - This is a dark variant that changes all colors to it s
#                       complementary counterpart giving the feeling of a new palette but
#                       that still makes sense with the image provided
#  * darkcomp16      - variation of the dark complementary variant
#  * harddark        - Same as dark with hard hue colors
#  * harddark16      - Harddark with color variation
#  * harddarkcomp    - complementary colors variation of harddark scheme
#  * harddarkcomp16  - complementary colors variation of harddark scheme
#  * light           - Light bg dark fg
#  * light16         - Same as light but uses the color trick
#  * lightcomp       - complementary colors variation of light
#  * lightcomp16     - complementary colors variation of light with the color variation
#  * softdark        - Variant of softlight uses the lightest colors and a dark background
#                       could be interpreted as dark inversed
#  * softdark16      - softdark with color variation
#  * softdarkcomp    - complementary variation for softdark
#  * softdarkcomp16  - complementary variation for softdark with the color variation
#  * softlight       - Light with soft pastel colors counterpart of harddark
#  * softlight16     - softlight with color variation
#  * softlightcomp   - softlight with complementary colors
#  * softlightcomp16 - softlight with complementary colors with colors

# Ensures a "readable contrast" (OPTIONAL, disabled by default)
# Should only be enabled when you notice an unreadable contrast frequently happening
# with your images. The reference color for the contrast is the background color.
check_contrast = true

[templates]
# template: A relative path that points to a file where wallust.toml is located, usually at `~/.config/wallust/`
# target: Absolute path in which to place a file with generated templated values
# NOTE: prefer '' over "" for paths, avoids escaping.
#zathura = { template = 'zathura', target = '~/.config/zathura/zathurarc' }

# OPTIONALLY It can accept `new_engine = true`: This "new engine" difers by using  double brackets like `{{variable}}`
# instead of one like usual, which helps with file formats that use brackets like json. With the `new_engine` enabled
# you can escape and produce a literal `{{` by `{{{{}}`, and for `}}` you escape it with `{{}}}}`.
#dunst = { template = 'dunstconfig', target = '~/.config/dunst/dunstrc', new_engine = true }

# template field can be express as `src` and target as `dst` for shorter naming:
#alacritty = { src = 'alacrittycfg', dst = '~/.config/alacritty/alacritty.toml' }
# As well as using dotted toml fields, both `alacritty` fields represent the same;
#alacritty.src = 'alacrittycfg'
#alacritty.dst = '~/.config/alacritty/alacritty.toml'

colors = { template = 'templates/colors', target = '~/.cache/wal/colors', pywal = true }
json = { template = 'templates/colors.json', target = '~/.cache/wal/colors.json' }
hyprland = { template = 'templates/colors-hyprland.conf', target = '~/.cache/wal/colors-hyprland.conf', pywal = true }
# zellij = { template = 'templates/colors-zellij.kdl', target = '~/.config/zellij/themes/colors-zellij.kdl', pywal = true }
vim = { template = 'templates/colors-wal.vim', target = '~/.cache/wal/colors-wal.vim', pywal = true }
kitty = { template = 'templates/colors-kitty.conf', target = '~/.cache/wal/colors-kitty.conf', pywal = true }

# REMINDER Variables and methods that can be used with templating:
#  wallpaper:  The full path to the current wallpaper, colorscheme file or the name of the theme in use.
#  backend:    Current **backend** being used.
#  colorspace: Current **colorspace** being used.
#  palette:     Current **palette** being used.
#  alpha:      Default to 100, can be modified in the config file or with `--alpha`/`-a`.
#  alpha_dec:  Instead of [0..=100], displays it from 0.00 to 1.00.
#  var:        Output the color in `hex`.
#  var.rgb:    Output the color in `rgb`.
#  var.rgba:   Output the color in `rgba`.
#  var.xrgba:  Output the color in `xrgb`.
#  var.strip:  Output the color in `hex` (without a `#`).
#  var.red:    Output the red value.
#  var.green:  Output the green value.
#  var.blue:   Output the blue value.
#
# Where `var` can be colors from `color0` to `color15`, `background`, `foreground` and `cursor`.
